import torch
import torch.nn as nn

from model.drifting import normalize_V, normalize_phi, compute_V_multi_tau


class DriftingLoss(nn.Module):
    """
    Implementation of the drifting loss objective for generative modeling
    The loss function minimizes the difference between the current prediction and a frozen drifted target:
    loss = E[||phi(x) - stopgrad(phi(x) + V(phi(x)))||^2]
    """
    def __init__(self, phi=None, tau_set=[0.02, 0.05, 0.2], use_normalize_phi=True, use_normalize_V=True, use_pixel_space=False):
        super().__init__()
        self.phi = phi
        self.tau_set = tau_set
        self.use_normalize_phi = use_normalize_phi
        self.use_normalize_V = use_normalize_V
        self.use_pixel_space = use_pixel_space

    def get_features(self, x):
        """
        Extract features phi(x) from input samples
        Uses pixel-level flattening if no encoder is provided or pixel space is specified
        """
        if self.use_pixel_space or self.phi is None:
            return x.flatten(start_dim=1)
        else:
            return self.phi(x)

    def forward(self, x, y_p, y_q=None):
        """
        Compute the drifting loss
        x: samples generated by the model (negative distribution q)
        y_p: samples from the data distribution (positive distribution p)
        y_q: alternative source of negative samples, defaults to x
        """
        if y_q is None:
            y_q = x

        # Extract features phi(x), phi(y_p), and phi(y_q)
        feat_q = self.get_features(x)
        feat_p = self.get_features(y_p)
        feat_neg = self.get_features(y_q)

        # Apply feature normalization scale S_j such that E[dist(phi(x), phi(y))] approx sqrt(C)
        if self.use_normalize_phi:
            feat_q, S_j = normalize_phi(feat_q)
            feat_p, _ = normalize_phi(feat_p, S_j=S_j)
            feat_neg, _ = normalize_phi(feat_neg, S_j=S_j)

        # Compute the aggregated drifting field V = V_p+ - V_q- across multiple temperatures tau
        V = compute_V_multi_tau(
            feat_q,
            feat_p,
            feat_neg,
            self.tau_set,
            mask_self=(y_q is x),
        )

        # Normalize the drift field V such that E[||V||^2 / C] approx 1
        if self.use_normalize_V:
            V = normalize_V(V)

        # Define the fixed-point target by stopping gradients on the drifted samples
        # target = stopgrad(phi(x) + V)
        target = (feat_q + V).detach()
        loss = torch.mean((feat_q - target) ** 2)

        info = {
            "loss": loss.item(),
            "drift_norm": torch.mean(V ** 2).item() ** 0.5,
            "feat_norm": torch.mean(feat_q ** 2).item() ** 0.5,
        }

        return loss, info


class ClassConditionalDriftingLoss(nn.Module):
    """
    Class-conditional drifting loss for guided generation using class labels
    Computes loss per class using same-class samples as positives
    Supports negative sample mixing for classifier-free guidance
    """
    def __init__(self, phi=None, tau_set=[0.02, 0.05, 0.2], use_pixel_space=False):
        super().__init__()
        self.phi = phi
        self.tau_set = tau_set
        self.use_pixel_space = use_pixel_space

    def get_features(self, x):
        """
        Extract features phi(x) for conditional inputs
        """
        if self.use_pixel_space or self.phi is None:
            return x.flatten(start_dim=1)
        else:
            return self.phi(x)

    def forward(self, x_gen, labels_gen, x_real, labels_real, x_uncond_neg=None):
        """
        Compute class-conditional loss over a batch
        Includes support for additional unconditional data as negatives
        Effective negative distribution: q_tilde = (1-gamma)*q_theta + gamma*p_data_uncond
        """
        device = x_gen.device
        num_classes = labels_gen.max().item() + 1

        total_loss = 0.0
        total_drift_norm = 0.0
        count = 0

        for c in range(num_classes):
            # Select samples belonging to the current class c
            mask_gen = labels_gen == c
            mask_real = labels_real == c

            if not mask_gen.any() or not mask_real.any():
                continue

            x_gen_c = x_gen[mask_gen]
            y_p_c = x_real[mask_real]

            # Collect negative samples: other classes in the batch or generated samples
            mask_neg = labels_gen != c
            y_q_c = x_gen[mask_neg] if mask_neg.any() else x_gen_c

            # Append unconditional negative samples if provided to support guidance
            if x_uncond_neg is not None and len(x_uncond_neg) > 0:
                y_q_c = torch.cat([y_q_c, x_uncond_neg], dim=0)

            # Map inputs to feature space phi
            feat_q = self.get_features(x_gen_c)
            feat_p = self.get_features(y_p_c)
            feat_neg = self.get_features(y_q_c)

            # Compute the drifting field V for the current class-conditional distribution
            V = compute_V_multi_tau(
                feat_q,
                feat_p,
                feat_neg,
                self.tau_set,
                mask_self=False,
            )
            total_drift_norm += torch.mean(V ** 2).item() ** 0.5 * len(x_gen_c)
            loss_for_logging = torch.mean(V ** 2)

            # Apply drift normalization factor lambda
            V = normalize_V(V)

            # Compute local MSE loss for the class-conditional equilibrium
            target = (feat_q + V).detach()
            loss_c = torch.mean((feat_q - target) ** 2)

            total_loss = total_loss + loss_c * len(x_gen_c)
            count += len(x_gen_c)

        if count == 0:
            return torch.tensor(0.0, device=device), {"loss": 0.0, "drift_norm": 0.0}

        # Return average loss weighted by the number of samples per class
        loss = total_loss / count

        info = {
            "loss": loss_for_logging.item(),
            "drift_norm": total_drift_norm,
        }

        return loss, info
